# Generated by Django 5.0.7 on 2024-07-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_showbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowBooking',
        ),
    ]
