# Generated by Django 5.0.7 on 2024-07-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='movie_theater',
        ),
        migrations.RemoveField(
            model_name='media',
            name='ticket_price',
        ),
    ]
