# Generated by Django 5.0.7 on 2024-07-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_media_movie_theater_remove_media_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('Recommended', 'Recommended'), ('Live Shows', 'Live Shows')], max_length=20),
        ),
    ]
