# Generated by Django 5.0.7 on 2024-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_media_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('Recommended', 'Recommended'), ('Live shows', 'Live shows'), ('All movies', 'All movies'), ('All shows', 'All shows')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
